name: e2e
services:
  semoss:
    image: "semoss/docker"
    ports:
      - 127.0.0.1:9091:8080
    environment:
      - SETSOCIAL=true
      - ENABLE_NATIVE=true
      - ENABLE_NATIVE_REGISTRATION=true
    command: /bin/bash -c "runCS.sh"
    networks:
      - tnet
    restart: always
    
  test:
    build: .
    depends_on:
      - semoss
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:
      - tnet

networks:
  tnet:
  
    